language: cpp
compiler: gcc
dist: trusty

# before_script: 
#  - cd csvTool

before_install:
  - cd csvTool
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script: 
  - g++ main.cpp -std=c++11 -o csvtool11
  - g++ main.cpp -std=c++14 -o csvtool14
  - g++ main.cpp -std=c++17 -o csvtool17
  - g++ main.cpp -std=c++11 -O2 -o csvtool11O2
